name: elementary_counter
description: Minimal Elementary MVVM example
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  elementary: ^3.2.0
  elementary_helper: 1.0.2
  state_notifier: ^1.0.0
  provider: ^6.0.5

flutter:
  uses-material-design: true